version: 2
jobs:
  build_and_test:
    working_directory: ~/projects/nishopping
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - checkout
      - setup_remote_docker
        docker_layer_caching: true
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: docker run (mysql)
          command: |
            set -x
            cd ./docker
            docker-compose up -d
            sleep 30
  #            docker run --network container:contacts

  mvn-test:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: circleci-demo-noShopping-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: circleci-demo-noShopping-{{ checksum "pom.xml" }}
      - run:
          name: test
          command: |
            cd ./backend
            mvn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - mvn-test:
          requires:
            - build